finished the bash script and added some color to make it look cool

diff --git a/compiler/llvm-compile b/compiler/llvm-compile
--- a/compiler/llvm-compile
+++ b/compiler/llvm-compile
@@ -13,7 +13,7 @@ ARGUMENTS:
 OPTIONS:
     -h,   Show this help message and exit
     -w,   Write Machine IR to a file, <filename>.txt
-    -r,   Print Machine IR to the output
+    -p,   Print Machine IR to the output
     -d,   Output files to subsequently given directory   
 
 EXAMPLES:
@@ -25,14 +25,16 @@ OUTPUT FILES:
     as the input file(s) unless specified with -d.
 EOF
 }
+#change colors of output to make it easier to debug/see errors
+RED='\033[0;31m'
+NC='\033[0m'
 
 # Source - https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script#59916
-SRC_DIR=$( dirname -- "$( readlink -f -- "$0"; )"; )
-echo "${SRC_DIR}"
+SRC_DIR=$( dirname -- "$( readlink -f -- "$0"; )"; ) # allows for symbolic linking
 
 #booleans to use for getopts
-write_machineIR=$false
-print_machineIR=$false
+write_machineIR=false
+print_machineIR=false
 OUTPUT_DIRECTORY=""
 
 if [[ $# -eq 0 ]]; then
@@ -40,24 +42,24 @@ if [[ $# -eq 0 ]]; then
     exit 1
 fi
 
-#getopts with out three options - see help() for more information
-while getopts ":hwrd:" option; do
+# getopts with 4 options - see help() for more information
+while getopts ":hwpd:" option; do
   case $option in
     h)
         compileHelp
         exit 0
         ;;
     w)
-        write_file=$true 
+        write_machineIR=true 
         ;;
-    r)
-        print_machineIR=$true
+    p)
+        print_machineIR=true
         ;;
     d)
         OUTPUT_DIRECTORY=${OPTARG}
         
         if [[ ! -d "$OUTPUT_DIRECTORY" ]]; then 
-            echo "${OUTPUT_DIRECTORY}: does not exist" >&2
+            echo -e "${RED}${OUTPUT_DIRECTORY}: No such directory${NC}" >&2
             exit 1
         fi
         ;;
@@ -75,7 +77,7 @@ shift $((OPTIND - 1))
 
 # Check if any files remain after processing options
 if [[ $# -eq 0 ]]; then
-    echo "Error: No input files specified" >&2
+    echo -e "${RED}Error: No input files specified${NC}" >&2
     exit 1
 fi
 
@@ -86,12 +88,27 @@ for file in $@; do
     filename_noextension_bpf="${filename_noextension%.*}"
 
     if [[ -f "$file" ]]; then
-        echo "${filename_noextension}.o Machine IR:"
-        # ${SRC_DIR}/llvm-project/build/bin/clang -emit-llvm -S ${filename} -O3 -target bpf -mcpu=duotronic -fno-unroll-loops
-        # ${SRC_DIR}/llvm-project/build/bin/llc -march=bpf -mcpu=duotronic -filetype=obj -o ${filename_noextension}.o -O0 --print-after-isel -bpf-stack-size=10000 ${filename_noextension}.ll
-        # ${SRC_DIR}/llvm-project/build/bin/llvm-objcopy -O binary --only-section=.text ${filename_noextension}.o ${filename_noextension_bpf}.o
+        ${SRC_DIR}/llvm-project/build/bin/clang -emit-llvm -S ${filename} -O3 -target bpf -mcpu=duotronic -fno-unroll-loops
+        OUTPUT=$(${SRC_DIR}/llvm-project/build/bin/llc -march=bpf -mcpu=duotronic -filetype=obj -o ${filename_noextension}.o -O0 --print-after-isel -bpf-stack-size=10000 ${filename_noextension}.ll 2>&1)
+        ${SRC_DIR}/llvm-project/build/bin/llvm-objcopy -O binary --only-section=.text ${filename_noextension}.o ${filename_noextension_bpf}.o
+
+        if [[ "$write_machineIR" = true ]]; then 
+            echo "${OUTPUT}" > ${filename_noextension_bpf}.txt
+        fi
+        if [[ "$print_machineIR" = true ]]; then 
+            echo "${filename_noextension}.o Machine IR:"
+            echo "${OUTPUT}"
+        fi
+
+        if [[ -d "$OUTPUT_DIRECTORY" ]]; then 
+            mv ${filename_noextension}.ll ${filename_noextension}.o ${filename_noextension_bpf}.o ${OUTPUT_DIRECTORY}
+            if [[ "$write_machineIR" = true ]]; then 
+                mv ${filename_noextension_bpf}.txt ${OUTPUT_DIRECTORY}
+            fi
+        fi
+        
     else
-        echo "$filename: No such file" >&2
+        echo -e "${RED}${filename}: No such file${NC}" >&2
     fi
 done
 
